import katex from "katex";

function escapeHTML(value: string): string {
  return value.replace(
    /[&<>"']/g,
    (character) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#39;",
      })[character] ?? character,
  );
}

/**
 * KaTeX output is generated by KaTeX, never inserted from the source value.
 * `trust: false` also keeps TeX HTML commands disabled at the trust boundary.
 */
export function renderSafeMath(value: string, displayMode: boolean): string {
  try {
    return katex.renderToString(value, {
      displayMode,
      output: "htmlAndMathml",
      throwOnError: false,
      trust: false,
    });
  } catch {
    // KaTeX should not throw with throwOnError:false, but keeping the source
    // visible makes even unexpected parser errors recoverable in the editor.
    return `<span class="math-render-error">${escapeHTML(value)}</span>`;
  }
}
